#### Config for cb-dragonfly ####

# influxdb connection info
influxdb:
  endpoint_url: http://cb-dragonfly-influxdb # endpoint for influxDB
  internal_port: 8086
  external_port: 28086
  database: cbmon
  user_name: cbmon
  password: password

kapacitor:
  endpoint_url: http://192.168.130.7:9093 # endpoint to kapacitor

# collect manager configuration info
collectManager:
  collector_ip: 192.168.130.7 # local access endpoint to cb-dragonfly API server
  collector_port: 8094    # udp port
  collectorGroup_count: 1      # default collector group count

# api server configuration info
apiServer:
  port: 9090

# monitoring interval configuration info
monitoring:
  agent_interval: 2        # agent interval (s)
  collector_interval: 10   # aggregate interval (s)
  max_host_count:  5       # maximum host count per collector
  monitoring_policy: 0      # 0 => The number of agent, 1 => csp group
